#ifndef KILOBOT_CALICO_DEFINITIONS_H
#define KILOBOT_CALICO_DEFINITIONS_H

#define MSG_MAX_SIZE 9

#define MSG_SET_MOTORS 1
#define MSG_SET_COLOR 2
#define MSG_SET_POS 3
#define MSG_SEND_MSG 4
#define MSG_SEND_BROADCAST 5
#define MSG_SEND_VS_BROADCAST 6

#endif
